#!/bin/bash

if [ ! -f .semver ]
then
    exit 0
fi

git tag -l | grep -q `semver tag`
if [ $? -eq 0 ]
then
  cat <<\EOF
Error: you can't commit with this version number, you have to bump to another patch, minor or major.
EOF
  exit 1
else
  exit 0
fi
